improve
eslint: fix prettier integration.
eslint: use warn instead of error for most rules.

children: removed in favor of mount.

pkg: update deps.
pkg: add sandbox projects as workspaces.

examples/counter: add simple counter example, using store from the new state module
examples/todo: begin implementation of "signals"

debug: use local variable instead of setting globally on window object

element: rename elementHelper to createElement

error: simplify usage of createError method.

events: add normalizeEvent method for stripping 'from' event name

hooks: remove triggerChildrenHooks since mount fires thos e hooks now.

memo: implement memoize method

mount: refactor initialization of component or element

state: add new state methods